# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Conduition
subtitle: ''
description: >-
  The personal blog of a pseudonymous cypherpunk. My specialties are cryptography,
  scriptless smart contracts, and multi-party computation.


  - [View my code on Github.](https://github.com/conduition) <a class="icon u-url" target="_blank" rel="noopener me" href="https://github.com/conduition" aria-label="github" title="github"><i class="fa-brands fa-github"></i></a>

  - Contact me by email at <a href="mailto:conduition@proton.me">conduition@proton.me</a>

  - [Download my PGP key here. <img src="/images/gnupg-logo.png" style="height: 14px;">](/meta/conduition.key.asc)


  [Follow me on Nostr](https://iris.to/npub1l6uy9chxyn943cmylrmukd3uqdq8h623nt2gxfh4rruhdv64zpvsx6zvtg).

    - Pubkey: `npub1l6uy9chxyn943cmylrmukd3uqdq8h623nt2gxfh4rruhdv64zpvsx6zvtg`
    - Profile: `nprofile1qqs0awzzutnzfj6cudj03a7txc7qxsrma9ge44yrym6337tkkd23qkg32nsh9`
    - NIP-05: `conduition@conduition.io`

  # My Work

  I maintain the [`secp`](https://crates.io/crates/secp) and [`musig2`](https://crates.io/crates/musig2)
  Rust crates, and love to contribute to cryptographic open source projects
  which pique my interest.


  Notice any errors in my work? Please let me know! 🧹
  <a href="mailto:conduition@proton.me">Contact me by email</a> or
  [suggest an edit on Github](https://github.com/conduition/conduition.io).

  # Hiring

  - 🕰️ I have years of experience working in the cryptocurrency industry and other
  security-centric work environments.

  - 🧑‍💻 I'm strongly proficient in Python, JavaScript, Golang, and Rust.

  - 💻 I have written and maintained front-end desktop apps used by hundreds of
  thousands of people.

  - 📡 I have designed and written back-end server architectures which securely process
  traffic from millions of clients.

  - 💸 I have earned thousands of USD in bug bounties.


  As you can also see from [my scribblings](/archives/), I'm the kind of developer
  who likes to dig deep into the highly technical mathematical inner workings of
  protocols which others take for granted.


  <a href="mailto:conduition@proton.me">Contact me by email</a> to discuss contract
  based consulting or development work payable in Bitcoin. I'll also consider
  long-term contracts or sponsorships depending on the subject matter.

keywords: bitcoin scriptless smart contracts blockchain crypto cryptography lightning network
author: Conduition
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://conduition.io
permalink: :category/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - .well-known/nostr.json
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus

mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: false # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
  packages: # extra packages to load
  extension_options: {}
    # you can put your extension options here
    # see http://docs.mathjax.org/en/latest/options/input/tex.html#tex-extension-options for more detail

deploy:
  type: rsync
  host: conduition.io
  user: root
  root: /var/www
  port: 22
  delete: true
  progress: true
  verbose: true
  ignore_errors: false
  create_before_update: false
  args: --chown=root:root
  # key: <key>
